name: "Terraform-Apply"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-west-2'
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

    steps:
      - uses: actions/checkout@v2
      - name: Calculate checksum
        run: |
          echo "sum=script.zip" >> $GITHUB_ENV
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python script and archive code
        run: |
          python create_s3_buckets.py 
          zip -r script.zip requirements.txt main.py
          echo "sum1=script.zip" >> $GITHUB_ENV  
      - name: Compare archives and upload code to s3
        run: |
          if [[ $(diff -y --suppress-common-lines  <(unzip -lqq ${{ env.sum }}) <(unzip -lqq ${{ env.sum1 }})) != "" ]];then
            aws s3 cp script.zip s3://scaling-fastapi-bucket-1
          fi
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - name: Deploy Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
